# Generated by Django 3.1.4 on 2021-02-10 18:09

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IskTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("time", models.DateTimeField()),
                (
                    "isk_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "isk",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="EEI", max_digits=20
                    ),
                ),
                (
                    "transaction_type",
                    models.TextField(
                        choices=[
                            ("price_change_broker_fee", "Price Change Broker Fee"),
                            ("broker_fee", "Broker Fee"),
                            ("transaction_tax", "Transaction Tax"),
                            ("contract_broker_fee", "Contract Broker Fee"),
                            ("contract_transaction_tax", "Contract Transaction Tax"),
                            ("contract_gross_profit", "Contract Gross Profit"),
                            (
                                "external_market_price_adjustment_fee",
                                "InGame Market Price Adjustment Fee",
                            ),
                            (
                                "external_market_gross_profit",
                                "InGame Market Gross Profit",
                            ),
                            ("egg_deposit", "Egg Deposit"),
                            ("fractional_remains", "Fractional Remains"),
                            ("buyback", "Buy Back"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EggTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("time", models.DateTimeField()),
                (
                    "eggs_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "eggs",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="EEI", max_digits=20
                    ),
                ),
                ("debt", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gooseuser",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="isktransaction",
            index=models.Index(fields=["time"], name="bank_isktra_time_24393a_idx"),
        ),
        migrations.AddIndex(
            model_name="eggtransaction",
            index=models.Index(fields=["time"], name="bank_eggtra_time_e20cc2_idx"),
        ),
    ]
