# Generated by Django 3.1.2 on 2020-11-24 16:47

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EggTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("time", models.DateTimeField()),
                (
                    "eggs_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "eggs",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="EEI", max_digits=20
                    ),
                ),
                ("debt", models.BooleanField(default=True)),
                ("counterparty_discord_username", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="IskTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("time", models.DateTimeField()),
                (
                    "isk_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "isk",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="EEI", max_digits=20
                    ),
                ),
                (
                    "transaction_type",
                    models.TextField(
                        choices=[
                            ("price_change_broker_fee", "Price Change Broker Fee"),
                            ("broker_fee", "Broker Fee"),
                            ("transaction_tax", "Transaction Tax"),
                            ("contract_broker_fee", "Contract Broker Fee"),
                            ("contract_transaction_tax", "Contract Transaction Tax"),
                            ("contract_gross_profit", "Contract Gross Profit"),
                            (
                                "external_market_price_adjustment_fee",
                                "InGame Market Price Adjustment Fee",
                            ),
                            (
                                "external_market_gross_profit",
                                "InGame Market Gross Profit",
                            ),
                            ("egg_deposit", "Egg Deposit"),
                            ("fractional_remains", "Fractional Remains"),
                            ("buyback", "Buy Back"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
    ]
