# Generated by Django 3.1.2 on 2020-11-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bank", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="isktransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.inventoryitem"
            ),
        ),
        migrations.AddField(
            model_name="eggtransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.inventoryitem"
            ),
        ),
        migrations.AddIndex(
            model_name="isktransaction",
            index=models.Index(fields=["time"], name="bank_isktra_time_24393a_idx"),
        ),
        migrations.AddIndex(
            model_name="eggtransaction",
            index=models.Index(fields=["time"], name="bank_eggtra_time_e20cc2_idx"),
        ),
    ]
