# Generated by Django 3.1.4 on 2021-01-12 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bank", "0002_auto_20201124_1647"),
    ]

    operations = [
        migrations.AddField(
            model_name="eggtransaction",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eggtransaction",
            name="counterparty_discord_username",
            field=models.TextField(blank=True, null=True),
        ),
    ]
