# Generated by Django 3.1.4 on 2021-01-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bank", "0004_populate_counterparty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eggtransaction",
            name="counterparty_discord_username",
        ),
        migrations.AlterField(
            model_name="eggtransaction",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.gooseuser"
            ),
        ),
    ]
