# Generated by Django 3.1.4 on 2021-03-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0010_corp_editable"),
        ("hordak", "0027_trigger_update_full_account_codes_effective"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCurrency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "api_type",
                    models.TextField(
                        choices=[("space_venmo", "space_venmo")], default="space_venmo"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hordak.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualCurrencyStorageAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hordak.account",
                    ),
                ),
                (
                    "corp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.corp"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venmo.virtualcurrency",
                    ),
                ),
                (
                    "pending_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_for",
                        to="hordak.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="virtualcurrency",
            name="corps",
            field=models.ManyToManyField(
                through="venmo.VirtualCurrencyStorageAccount", to="users.Corp"
            ),
        ),
        migrations.AddField(
            model_name="virtualcurrency",
            name="withdrawal_characters",
            field=models.ManyToManyField(blank=True, to="users.Character"),
        ),
    ]
