# Generated by Django 3.1.4 on 2021-03-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hordak", "0027_trigger_update_full_account_codes_effective"),
        ("venmo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcurrency",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hordak.account",
            ),
        ),
    ]
