# Generated by Django 3.1.4 on 2021-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venmo", "0002_auto_20210313_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcurrency",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
