# Generated by Django 3.1.4 on 2021-03-13 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venmo", "0003_virtualcurrency_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcurrency",
            name="default",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="virtualcurrency",
            name="name",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]+$",
                        message="Currency Name must be Alphanumeric with no spaces",
                    )
                ],
            ),
        ),
    ]
