# Generated by Django 3.1.4 on 2021-03-13 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venmo", "0004_auto_20210313_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcurrency",
            name="name",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+$",
                        message="Currency Name must be all lowercase Alphanumeric with no spaces",
                    )
                ],
            ),
        ),
    ]
