# Generated by Django 3.1.4 on 2021-05-15 14:36

from django.db import migrations, models
import django.db.models.deletion
import goosetools.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0001_initial"),
        ("users", "0016_auto_20210508_1403"),
        ("venmo", "0005_auto_20210313_1832"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("via_contract", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
                ("deposit_command_format", models.TextField(blank=True, null=True)),
                (
                    "transfer_prefix_command_format",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "transfer_user_command_format",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "transfer_postfix_command_format",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "access_controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.crudaccesscontroller",
                    ),
                ),
                (
                    "auto_send_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord_bot.discordchannel",
                    ),
                ),
                (
                    "virtual_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venmo.virtualcurrency",
                    ),
                ),
            ],
            bases=(goosetools.users.models.AccessControlledModel, models.Model),
        ),
    ]
