# Generated by Django 3.1.4 on 2021-05-15 15:53

from django.db import migrations, models
import django.db.models.deletion
import goosetools.venmo.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210508_1403"),
        ("venmo", "0007_auto_20210515_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermethod",
            name="access_controller",
            field=models.ForeignKey(
                default=goosetools.venmo.models.create_access_controller,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.crudaccesscontroller",
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="If this should become the default transfer method",
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="transfer_type",
            field=models.TextField(
                choices=[
                    ("contract", "Via In Game Contracts"),
                    ("generate_command", "Generates a command for the user to send"),
                ]
            ),
        ),
    ]
