# Generated by Django 3.1.4 on 2021-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venmo", "0008_auto_20210515_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfermethod",
            name="generated_command_help_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
