# Generated by Django 3.1.4 on 2021-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venmo", "0009_transfermethod_generated_command_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermethod",
            name="deposit_command_format",
            field=models.TextField(
                blank=True,
                help_text="This is the template used to generate an initial 'deposit' command the user should send before doing the transfer. If you include anyof the following pieces of text they will be replaced with their corresponding value when a command is generated: TRANSFERRING_DISCORD_USER, TOTAL_TRANSFER_AMOUNT, TOTAL_TRANSFER_AMOUNT_WITHOUT_TRANSFERRING_USERS_AMOUNT",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="generated_command_help_text",
            field=models.TextField(
                blank=True,
                help_text="This will be displayed before any commands generated for a transferring user and should explain where to send the commands and how to use them.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="transfer_postfix_command_format",
            field=models.TextField(
                blank=True,
                help_text="This is the template used to generate the end of a 'transfer' command the user should send to actually perform the transfer. If you include any of the following pieces of text they will be replaced with their corresponding value when a command is generated: TRANSFERRING_DISCORD_USER, TOTAL_TRANSFER_AMOUNT, TOTAL_TRANSFER_AMOUNT_WITHOUT_TRANSFERRING_USERS_AMOUNT",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="transfer_prefix_command_format",
            field=models.TextField(
                blank=True,
                help_text="This is the template used to generate the start of a 'transfer' command the user should send to actually perform the transfer. If you include any of the following pieces of text they will be replaced with their corresponding value when a command is generated: TRANSFERRING_DISCORD_USER, TOTAL_TRANSFER_AMOUNT, TOTAL_TRANSFER_AMOUNT_WITHOUT_TRANSFERRING_USERS_AMOUNT",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfermethod",
            name="transfer_user_command_format",
            field=models.TextField(
                blank=True,
                help_text="This is the template used per user who is being transfered profit and will be repeated between the prefix and postfix for every user to generate the entire transfer command.If you include any of the following pieces of text they will be replaced with their corresponding value when a command is generated: USER_TO_TRANSFER_TO, USER_TRANSFER_AMOUNT",
                null=True,
            ),
        ),
    ]
