default_language_version:
  python: python3.8

ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/prospector
    rev: v1.12.1
    hooks:
      - id: prospector
        # Exciting bash to support running inside docker or a local virtual env.
        entry: bash -c "poetry shell; python -m prospector -X . ;"
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        language: system
        name: Run pylint only on changed files.
        entry: bash -c "pylint `git diff --name-only --diff-filter=d HEAD^ | grep -E '\.py$' | tr '\n' ' '`"
        types: ["python"]
        pass_filenames: false
