default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        language: system
        name: Run MyPy typing checks.
        entry: bash -c "PYTHONPATH=$(pwd):$PYTHONPATH mypy ."
        pass_filenames: false
        verbose: true
        types: ["python"]
  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
      - id: prospector
        # Exciting bash to support running inside docker or a local virtual env.
        entry: bash -c "poetry shell; python -m prospector -X . ;"
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        language: system
        name: Run pylint only on changed files.
        entry: bash -c "pylint `git diff --name-only --diff-filter=d HEAD^ | grep -E '\.py$' | tr '\n' ' '`"
        types: ["python"]
        pass_filenames: false
  # - repo: local
  #   hooks:
  #     - id: migrations-check
  #       language: system
  #       name: Check for uncreated migrations.
  #       entry: bash -c "./manage.py makemigrations --check --dry-run"
  #       types: ["python"]
  #       pass_filenames: false
