version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: goosetools_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./.envs/.local/.django/:/app/.env
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:12
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5600:5432"
