version: '3'

# Test version of local.yml without volumes as we don't want to persist the test database between runs and using a different django port not to clash.

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: goosetools_local_django
    depends_on:
      - postgres_test
    volumes:
      - .:/app
      - ./.envs/.test/.django/:/app/.env
    env_file:
      - ./.envs/.test/.postgres
    command: /start

  postgres_test:
    image: postgres:12
    env_file:
      - ./.envs/.test/.postgres

  firefox:
    image: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20201009
    volumes:
      - /dev/shm:/dev/shm
