# Generated by Django 3.1.2 on 2020-10-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleettype",
            name="material_icon",
            field=models.TextField(default="attach_money"),
            preserve_default=False,
        ),
    ]
