# Generated by Django 3.1.2 on 2020-10-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fleettype_material_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='expected_duration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
