# Generated by Django 3.1.2 on 2020-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fleet_expected_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="user",
        ),
        migrations.AddField(
            model_name="character",
            name="discord_id",
            field=models.TextField(default="NA"),
            preserve_default=False,
        ),
    ]
