# Generated by Django 3.1.2 on 2020-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fleet_gives_shares_to_alts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetmember',
            name='admin_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
