# Generated by Django 3.1.2 on 2020-10-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0012_auto_20201017_0804")]

    operations = [
        migrations.AlterField(
            model_name="lootgroup",
            name="fleet_anom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fleetanom",
            ),
        ),
        migrations.AlterField(
            model_name="lootgroup",
            name="killmail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.killmail",
            ),
        ),
    ]
