# Generated by Django 3.1.2 on 2020-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201017_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='net_sold_at_price',
            new_name='total_profit',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='net_sold_at_price_currency',
            new_name='total_profit_currency',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
