# Generated by Django 3.1.2 on 2020-10-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201017_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lootshare',
            unique_together={('character', 'loot_group')},
        ),
    ]
