# Generated by Django 3.1.2 on 2020-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0020_auto_20201018_1244")]

    operations = [
        migrations.AddField(
            model_name="gooseuser",
            name="market_fee",
            field=models.DecimalField(decimal_places=4, default=25.0, max_digits=7),
        )
    ]
