# Generated by Django 3.1.2 on 2020-10-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20201018_1320"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="transaction_fee",
            new_name="transaction_tax",
        ),
    ]
