# Generated by Django 3.1.2 on 2020-10-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0025_auto_20201021_1217")]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.itemlocation"
            ),
        )
    ]
