# Generated by Django 3.1.2 on 2020-10-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0032_solditem_deposit_approved")]

    operations = [
        migrations.AlterField(
            model_name="junkeditem",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.inventoryitem"
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.inventoryitem"
            ),
        ),
        migrations.AlterField(
            model_name="solditem",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.inventoryitem"
            ),
        ),
    ]
