# Generated by Django 3.1.2 on 2020-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0036_auto_20201023_0940")]

    operations = [
        migrations.AddField(
            model_name="eggtransaction",
            name="debt",
            field=models.BooleanField(default=True),
        )
    ]
