# Generated by Django 3.1.2 on 2020-10-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20201026_0920"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="discord_avatar_url",
        ),
        migrations.RemoveField(
            model_name="character",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="character",
            name="discord_username",
        ),
        migrations.AlterField(
            model_name="character",
            name="discord_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.discorduser"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="ingame_name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="default_character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.character"
            ),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="discord_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.discorduser"
            ),
        ),
        migrations.DeleteModel(
            name="EggDeposit",
        ),
    ]
