# Generated by Django 3.1.2 on 2020-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20201026_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="verified",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
