# Generated by Django 3.1.2 on 2020-10-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0042_character_verified")]

    operations = [
        migrations.RemoveField(model_name="characterlocation", name="station"),
        migrations.AddField(
            model_name="characterlocation",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.system",
            ),
        ),
    ]
