# Generated by Django 3.1.2 on 2020-10-26 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0044_auto_20201026_1914")]

    operations = [
        migrations.RemoveField(model_name="contract", name="from_char"),
        migrations.AddField(
            model_name="contract",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="from_user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_contracts",
                to="core.gooseuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.TextField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("accepted", "accepted"),
                ],
                default="pending",
            ),
            preserve_default=False,
        ),
    ]
