# Generated by Django 3.1.2 on 2020-10-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20201028_0815"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemfiltergroup",
            name="anom_type",
        ),
        migrations.CreateModel(
            name="ItemFilterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "anom_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.anomtype"
                    ),
                ),
                (
                    "item_filter_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.itemfiltergroup",
                    ),
                ),
            ],
        ),
    ]
