# Generated by Django 3.1.2 on 2020-10-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0053_auto_20201028_1134")]

    operations = [
        migrations.RenameModel(old_name="ItemFilterGroup2", new_name="ItemFilterGroup")
    ]
