# Generated by Django 3.1.2 on 2020-10-28 15:12

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [("core", "0054_auto_20201028_1135")]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[core.models.UnicodeAndSpacesUsernameValidator],
            ),
        )
    ]
