# Generated by Django 3.1.2 on 2020-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20201028_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isktransaction',
            name='transaction_type',
            field=models.TextField(choices=[('price_change_broker_fee', 'Price Change Broker Fee'), ('broker_fee', 'Broker Fee'), ('transaction_tax', 'Transaction Tax'), ('contract_broker_fee', 'Contract Broker Fee'), ('contract_transaction_tax', 'Contract Transaction Tax'), ('contract_gross_profit', 'Contract Gross Profit'), ('external_market_price_adjustment_fee', 'InGame Market Price Adjustment Fee'), ('external_market_gross_profit', 'InGame Market Gross Profit'), ('egg_deposit', 'Egg Deposit')]),
        ),
    ]
