# Generated by Django 3.1.2 on 2020-10-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20201030_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmarketdataevent',
            old_name='highest_sell',
            new_name='highest_buy',
        ),
        migrations.RenameField(
            model_name='itemmarketdataevent',
            old_name='lowest_buy',
            new_name='lowest_sell',
        ),
    ]
