# Generated by Django 3.1.2 on 2020-10-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_auto_20201030_0732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="buy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="highest_buy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="lowest_sell",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="sell",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
