# Generated by Django 3.1.2 on 2020-10-14 09:28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_fleet_loot_was_stolen"),
    ]

    operations = [
        migrations.CreateModel(
            name="LootType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="fleet",
            name="loot_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.loottype"
            ),
        ),
        migrations.AddField(
            model_name="loottype",
            name="material_icon",
            field=models.TextField(default="star"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loottype",
            name="material_colour",
            field=models.TextField(default="lime lighten-3"),
            preserve_default=False,
        ),
    ]
