# Generated by Django 3.1.2 on 2020-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0071_fleet_loottype")]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.TextField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("accepted", "accepted"),
                    ("cancelled", "cancelled"),
                ]
            ),
        )
    ]
