# Generated by Django 3.1.2 on 2020-11-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_fleet_loottype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='loot_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loottype'),
            preserve_default=False,
        ),
    ]
