# Generated by Django 3.1.2 on 2020-11-13 13:06

from core.models import SoldItem
from django.db import migrations, models

def set_historical_transfered(apps, schema_editor):
    for sold_item in SoldItem.objects.all():
        sold_item.transfered = sold_item.transfered_to_participants
        sold_item.save()

class Migration(migrations.Migration):


    dependencies = [
        ("core", "0072_auto_20201110_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="solditem",
            name="transfered",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_historical_transfered),
    ]
