# Generated by Django 3.1.2 on 2020-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_auto_20201110_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="solditem",
            name="transfered",
            field=models.BooleanField(default=False),
        ),
    ]
