# Generated by Django 3.1.2 on 2020-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_solditem_transfered"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="all_done",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="deposit_command",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="transfer_command",
            field=models.TextField(default=""),
        ),
    ]
