# Generated by Django 3.1.2 on 2020-11-13 17:14

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0074_auto_20201113_1535")]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="own_share",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="EEI",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="own_share_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EEI", "Eve Echoes ISK")],
                default="EEI",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="own_share_in_eggs",
            field=models.BooleanField(default=True),
        ),
    ]
