# Generated by Django 3.1.2 on 2020-11-16 16:55

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_auto_20201115_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[core.models.UnicodeAndSpacesUsernameValidator()],
            ),
        ),
    ]
