# Generated by Django 3.1.2 on 2020-11-17 15:29

from django.db import migrations, models

from core.models import SoldItem


def set_historical_transfered(_apps, _schema_editor):
    for sold_item in SoldItem.objects.all():
        if sold_item.transfered and sold_item.isk_balance().amount > 10000:
            sold_item.transfered_quantity = 0
        else:
            sold_item.transfered_quantity = sold_item.quantity

        sold_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_auto_20201116_1655"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solditem",
            name="deposit_approved",
        ),
        migrations.RemoveField(
            model_name="solditem",
            name="deposited_into_eggs",
        ),
        migrations.RemoveField(
            model_name="solditem",
            name="transfered_to_participants",
        ),
        migrations.AddField(
            model_name="solditem",
            name="transfered_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_historical_transfered),
    ]
