# Generated by Django 3.1.2 on 2020-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_auto_20201116_1655"),
    ]

    operations = [
        migrations.AddField(
            model_name="lootgroup",
            name="name",
            field=models.TextField(blank=True, null=True),
        )
    ]
