# Generated by Django 3.1.2 on 2020-11-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_remove_character_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discorduser",
            name="unknown",
        ),
    ]
