# Generated by Django 3.1.2 on 2020-11-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_remove_discorduser_unknown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="fleet_type",
        ),
        migrations.RemoveField(
            model_name="fleet",
            name="loot_was_stolen",
        ),
        migrations.DeleteModel(
            name="FleetType",
        ),
    ]
