# Generated by Django 3.1.2 on 2020-11-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_auto_20201120_1049"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="fleet",
                    name="fc",
                ),
                migrations.AlterUniqueTogether(
                    name="fleetmember",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="fleetmember",
                    name="character",
                ),
                migrations.RemoveField(
                    model_name="fleetmember",
                    name="fleet",
                ),
            ],
            database_operations=[],
        )
    ]
