# Generated by Django 3.1.2 on 2020-11-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_auto_20201120_1345"),
        ("fleets", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="fleetanom",
                    name="fleet",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleets.fleet"
                    ),
                ),
                migrations.AlterField(
                    model_name="killmail",
                    name="fleet",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleets.fleet"
                    ),
                ),
                migrations.AlterField(
                    model_name="lootbucket",
                    name="fleet",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleets.fleet"
                    ),
                ),
                migrations.DeleteModel(
                    name="Fleet",
                ),
                migrations.DeleteModel(
                    name="FleetMember",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Fleet", table="fleets_fleet"),
                migrations.AlterModelTable(
                    name="FleetMember", table="fleets_fleetmember"
                ),
            ],
        ),
    ]
