# Generated by Django 3.1.4 on 2021-01-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLimitGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("days_between_orders", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("tech_level", models.PositiveIntegerField()),
                ("free", models.BooleanField(default=False)),
                (
                    "isk_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "isk_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="EEI",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "eggs_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "eggs_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="EEI",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("prices_last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "order_limit_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="industry.orderlimitgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_made", models.BooleanField(default=False)),
                ("uid", models.TextField(unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("state", django_fsm.FSMField(default="not_started", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.TextField(
                        choices=[
                            ("eggs", "eggs"),
                            ("isk", "isk"),
                            ("free", "free"),
                            ("srp", "srp"),
                        ]
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="EEI",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("payment_taken", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.character",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="industry.ship"
                    ),
                ),
            ],
        ),
    ]
