# Generated by Django 3.1.4 on 2021-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0002_auto_20210118_1719"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shiporder",
            index=models.Index(
                fields=["-created_at"], name="industry_sh_created_d92183_idx"
            ),
        ),
    ]
