# Generated by Django 3.1.4 on 2021-02-08 08:36

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields

# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    Ship = apps.get_model("industry", "Ship")
    ShipCopy = apps.get_model("industry", "ShipCopy")
    ShipOrder = apps.get_model("industry", "ShipOrder")
    for s in Ship.objects.all():
        ShipCopy.objects.create(
            name=s.name,
            tech_level=s.tech_level,
            free=s.free,
            isk_price=s.isk_price,
            eggs_price=s.eggs_price,
            prices_last_updated=s.prices_last_updated,
            order_limit_group=s.order_limit_group,
        )

    for so in ShipOrder.objects.all():
        so.ship_new_id = ShipCopy.objects.filter(name=so.ship.name).first().id
        so.save()


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0003_auto_20210120_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipCopy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("tech_level", models.PositiveIntegerField()),
                ("free", models.BooleanField(default=False)),
                (
                    "isk_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "isk_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="EEI",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "eggs_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EEI", "Eve Echoes ISK")],
                        default="EEI",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "eggs_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="EEI",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("prices_last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "order_limit_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="industry.orderlimitgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiporder",
            name="ship_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="industry.shipcopy",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
