# Generated by Django 3.1.4 on 2021-02-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0004_auto_20210208_0836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiporder",
            name="ship",
        ),
        migrations.RenameField(
            model_name="shiporder", old_name="ship_new", new_name="ship"
        ),
        migrations.DeleteModel(name="ship"),
        migrations.RenameModel(old_name="shipcopy", new_name="ship"),
    ]
