# Generated by Django 3.1.4 on 2021-02-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0005_auto_20210208_0856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiporder",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="industry.ship"
            ),
        ),
    ]
