# Generated by Django 3.1.2 on 2020-12-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0007_auto_20201202_1048"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiporder",
            name="order_limit_group",
        ),
        migrations.AddField(
            model_name="ship",
            name="order_limit_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="industry.orderlimitgroup",
            ),
        ),
    ]
