# Generated by Django 3.1.2 on 2020-12-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0009_shiporder_blocked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiporder",
            name="payment_method",
            field=models.TextField(
                choices=[
                    ("eggs", "eggs"),
                    ("isk", "isk"),
                    ("free", "free"),
                    ("srp", "srp"),
                ]
            ),
        ),
    ]
