# Generated by Django 3.1.2 on 2020-12-04 14:59

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0010_auto_20201203_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="eggs_price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="EEI",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="eggs_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EEI", "Eve Echoes ISK")],
                default="EEI",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="isk_price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="EEI",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="isk_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EEI", "Eve Echoes ISK")],
                default="EEI",
                editable=False,
                max_length=3,
            ),
        ),
    ]
