# Generated by Django 3.1.2 on 2020-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0012_auto_20201204_1640"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="prices_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
