# Generated by Django 3.1.2 on 2020-11-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        ("ownership", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solditem",
            name="transfer_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ownership.transferlog",
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="items.inventoryitem"
            ),
        ),
    ]
