# Generated by Django 3.1.4 on 2021-05-03 08:20

from django.db import migrations, models, connection
import django.db.models.deletion

# noinspection PyPep8Naming
# pylint: disable=unused-argument
def populate_fk(apps, schema_editor):
    # Truncate we'll resync with api later.
    cursor = connection.cursor()
    cursor.execute("TRUNCATE TABLE pricing_itemmarketdataevent")


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_inventoryitem_echoes_item"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmarketdataevent",
            name="echoes_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.echoesitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemmarketdataevent",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.RunPython(populate_fk),
    ]
