# Generated by Django 3.1.4 on 2021-05-03 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_inventoryitem_echoes_item"),
        ("pricing", "0002_auto_20210503_0820"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemmarketdataevent",
            name="item",
        ),
        migrations.RenameField(
            model_name="itemmarketdataevent", old_name="echoes_item", new_name="item"
        ),
    ]
