# Generated by Django 3.1.4 on 2021-05-03 19:32

from django.db import migrations, connection


# noinspection PyPep8Naming
# pylint: disable=unused-argument
def clear_data(apps, schema_editor):
    # Truncate we'll resync with api later.
    cursor = connection.cursor()
    cursor.execute("TRUNCATE TABLE pricing_itemmarketdataevent")


# noinspection PyPep8Naming
# pylint: disable=unused-argument
def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0011_auto_20210503_1822"),
        ("pricing", "0003_auto_20210503_0844"),
    ]

    operations = [
        migrations.RunPython(clear_data, reverse),
        migrations.AlterUniqueTogether(
            name="itemmarketdataevent",
            unique_together={("item", "time")},
        ),
    ]
