# Generated by Django 3.1.4 on 2021-07-15 18:40

from django.db import migrations, models


# noinspection PyPep8Naming
# pylint: disable=unused-argument
def set_live_as_undeletable(apps, schema_editor):
    PriceList = apps.get_model("pricing", "PriceList")
    live = PriceList.objects.get(name="eve-echoes-market.com live prices")
    live.deletable = False
    live.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0006_auto_20210607_0724"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_live_as_undeletable),
    ]
