# Generated by Django 3.1.4 on 2021-07-15 19:17

from django.db import migrations, models
import django.db.models.deletion
import goosetools.venmo.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210508_1403"),
        ("pricing", "0007_pricelist_deletable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="access_controller",
            field=models.ForeignKey(
                default=goosetools.venmo.models.create_access_controller_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.crudaccesscontroller",
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="api_type",
            field=models.TextField(
                choices=[
                    ("eve_echoes_market", "eve_echoes_market.com"),
                    ("google_sheet", "A Google Sheet"),
                    ("manual", "Manually Entered In GooseTools"),
                ]
            ),
        ),
    ]
