# Generated by Django 3.1.4 on 2021-07-24 08:32

import django.db.models.deletion
from django.db import migrations, models


# noinspection PyPep8Naming
# pylint: disable=unused-argument
def populate_latest(apps, schema_editor):
    ItemMarketDataEvent = apps.get_model("pricing", "ItemMarketDataEvent")
    LatestItemMarketDataEvent = apps.get_model("pricing", "LatestItemMarketDataEvent")
    PriceList = apps.get_model("pricing", "PriceList")

    ItemMarketDataEvent.objects.filter(price_list__isnull=True).delete()

    for price_list in PriceList.objects.all():
        print(f"Updating {price_list.name}, running big query first...")
        print("Running count query")
        unqiue_items = (
            ItemMarketDataEvent.objects.values("item")
            .filter(price_list=price_list)
            .distinct()
        )
        count = unqiue_items.count()
        print(f"Have {count} to work through")
        print_count = int(count / 100)
        i = 0
        for item in unqiue_items:
            latest = (
                ItemMarketDataEvent.objects.filter(
                    price_list=price_list, item_id=item["item"]
                )
                .order_by("-time")
                .first()
            )
            if i % print_count == 0:
                print(f"Up to {i}/{count}", end="\r")
            LatestItemMarketDataEvent.objects.create(
                price_list=latest.price_list,
                item=latest.item,
                time=latest.time,
                event=latest,
            )
            i += 1


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0011_auto_20210503_1822"),
        ("pricing", "0009_auto_20210718_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="price_type",
            field=models.TextField(
                choices=[("raw_market_data", "raw_market_data"), ("order", "order")],
                default="raw_market_data",
            ),
        ),
        migrations.AddField(
            model_name="itemmarketdataevent",
            name="unique_user_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="price_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pricing.pricelist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemmarketdataevent",
            unique_together={("price_list", "unique_user_id", "item", "time")},
        ),
        migrations.CreateModel(
            name="LatestItemMarketDataEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.itemmarketdataevent",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricelist",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="latestitemmarketdataevent",
            index=models.Index(
                fields=["price_list", "item", "time"],
                name="pricing_lat_price_l_0f6f05_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="latestitemmarketdataevent",
            unique_together={("price_list", "item")},
        ),
        migrations.RunPython(populate_latest),
    ]
