# Generated by Django 3.1.4 on 2021-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0010_auto_20210724_0834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="manual_override_price",
            field=models.BooleanField(
                default=False,
                help_text="If this price should override any current or future automatically downloaded prices.",
            ),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="time",
            field=models.DateTimeField(help_text="The time this price is for."),
        ),
        migrations.AlterField(
            model_name="itemmarketdataevent",
            name="unique_user_id",
            field=models.TextField(
                blank=True,
                help_text="An optional unique ID you want to give this price.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="price_type",
            field=models.TextField(
                choices=[("raw_market_data", "raw_market_data"), ("order", "order")],
                default="raw_market_data",
                help_text="Controls how these prices are treated. If raw_market_data then each price is just treated as an immutable 'the price for this item at this time is this' piece of data. If order then instead treated as the fact that you want to buy or sell the volume of the item and if hooked up to a shop then will make said order available in the system. The order's volume with be automatically decreased as orders are completed in the system, unless a new row is imported with a new unique_user_id which will update the volume and hence the order quantity to that rows volume.",
            ),
        ),
    ]
