# Generated by Django 3.1.4 on 2021-08-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0012_auto_20210807_1301"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataset",
            old_name="price_type",
            new_name="data_set_type",
        ),
    ]
