# Generated by Django 3.1.4 on 2021-01-14 15:31

from django.db import migrations, models
from goosetools.tenants.models import SiteUser


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    GooseUser = apps.get_model("users", "GooseUser")
    for user in GooseUser.objects.filter().all():
        site_user = SiteUser(
            username=user.username,
            first_name=user.first_name or "",
            last_name=user.last_name or "",
            email=user.email or "",
            is_staff=user.is_staff,
            is_active=user.is_active,
            date_joined=user.date_joined,
            password=user.password or "",
            last_login=user.last_login,
            is_superuser=user.is_superuser,
        )
        site_user.save()


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
            ],
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
