# Generated by Django 3.1.4 on 2021-01-14 15:31

from django.db import migrations
from goosetools.tenants.models import SiteUser


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    GooseUser = apps.get_model("users", "GooseUser")
    for user in GooseUser.objects.filter().all():
        user.site_user_id = SiteUser.objects.get(username=user.username).id
        user.save()


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
