# Generated by Django 3.1.4 on 2021-02-13 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_client_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="The name of your organization.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator("^[a-z0-9_]{1,100}$")
                ],
            ),
        ),
    ]
