# Generated by Django 3.1.4 on 2021-02-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_auto_20210213_1108"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalItemType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="GlobalRegion",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalSystem",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("jumps_to_jita", models.PositiveIntegerField(blank=True, null=True)),
                ("security", models.TextField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.globalregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalItemSubType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.globalitemtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalItemSubSubType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "item_sub_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.globalitemsubtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalItem",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                (
                    "eve_echoes_market_id",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                (
                    "cached_lowest_sell",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.globalitemsubsubtype",
                    ),
                ),
            ],
        ),
    ]
