# Generated by Django 3.1.4 on 2021-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_auto_20210115_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
