# Generated by Django 3.1.4 on 2021-05-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0005_globalitem_globalitemsubsubtype_globalitemsubtype_globalitemtype_globalregion_globalsystem",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalitemsubsubtype",
            name="item_sub_type",
        ),
        migrations.RemoveField(
            model_name="globalitemsubtype",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="globalsystem",
            name="region",
        ),
        migrations.DeleteModel(
            name="GlobalItem",
        ),
        migrations.DeleteModel(
            name="GlobalItemSubSubType",
        ),
        migrations.DeleteModel(
            name="GlobalItemSubType",
        ),
        migrations.DeleteModel(
            name="GlobalItemType",
        ),
        migrations.DeleteModel(
            name="GlobalRegion",
        ),
        migrations.DeleteModel(
            name="GlobalSystem",
        ),
    ]
