# Generated by Django 3.1.4 on 2021-01-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingame_name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Corp",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("full_name", models.TextField(blank=True, null=True, unique=True)),
                ("required_discord_role", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordGuild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.TextField()),
                ("member_role_id", models.TextField(blank=True, null=True)),
                ("bot_token", models.TextField()),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GooseUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(default="Europe/London"),
                ),
                (
                    "broker_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=5,
                        verbose_name="Your Broker Fee in %",
                    ),
                ),
                (
                    "transaction_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        verbose_name="Your Transaction Tax in %",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="unapproved",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("sa_profile", models.TextField(blank=True, null=True)),
                (
                    "default_character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.character",
                    ),
                ),
                (
                    "site_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_vouches",
                        to="users.gooseuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="unapproved",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("application_notes", models.TextField(blank=True, null=True)),
                ("ingame_name", models.TextField(blank=True, null=True)),
                ("previous_alliances", models.TextField(blank=True, null=True)),
                ("activity", models.TextField(blank=True, null=True)),
                ("looking_for", models.TextField(blank=True, null=True)),
                (
                    "corp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.corp"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gooseuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscordRoleDjangoGroupMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.TextField()),
                ("grants_staff", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.discordguild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorpApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="unapproved",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.character",
                    ),
                ),
                (
                    "corp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.corp"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="corp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.corp",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.gooseuser"
            ),
        ),
    ]
