# Generated by Django 3.1.4 on 2021-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corp",
            name="auto_approve",
            field=models.BooleanField(default=False),
        ),
    ]
