# Generated by Django 3.1.4 on 2021-01-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210119_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signup_required", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "connected_discord_server_id",
                    models.TextField(blank=True, null=True),
                ),
                ("code_of_conduct", models.TextField(blank=True, null=True)),
                ("sign_up_introduction", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("discord_role_uid", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SignUpQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.TextField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("textarea", "large text area"),
                            ("multichoice_dropdown", "multiple choice dropdown"),
                        ]
                    ),
                ),
                (
                    "auth_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.authconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.TextField(
                        choices=[
                            (
                                "basic_access",
                                "Able to Apply to join and view the home page and other basic registered user pages",
                            ),
                            ("loot_tracker", "Able to use the loot tracker"),
                            (
                                "loot_tracker_admin",
                                "Automatically an admin in every fleet and able to do loot buyback",
                            ),
                            (
                                "user_admin",
                                "Able to approve user applications and manage users",
                            ),
                            (
                                "single_corp_admin",
                                "Able to approve corp applications for a specific corp",
                            ),
                            (
                                "all_corp_admin",
                                "Able to approve corp applications for all corps and manage characters in that corp",
                            ),
                            ("ship_orderer", "Able to place ship orders"),
                            ("free_ship_orderer", "Able to place free ship orders"),
                            (
                                "ship_order_admin",
                                "Able to claim and work on ship orders",
                            ),
                            (
                                "ship_order_price_admin",
                                "Able to add/remove ship types and set if they are free or not",
                            ),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "corp",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.corp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermissionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "linked_discord_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.discordrole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermissionGroupMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userpermissiongroup",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userpermission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userpermissiongroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gooseuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignUpQuestionChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                (
                    "linked_discord_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.discordrole",
                    ),
                ),
                (
                    "signup_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.signupquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authconfig",
            name="new_user_discord_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.discordrole",
            ),
        ),
    ]
