# Generated by Django 3.1.4 on 2021-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_corp_auto_approve"),
    ]

    operations = [
        migrations.AddField(
            model_name="goosegroup",
            name="manually_given",
            field=models.BooleanField(default=False),
        ),
    ]
