# Generated by Django 3.1.2 on 2020-12-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_discordguild_discordroledjangogroupmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
