# Generated by Django 3.1.4 on 2021-02-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_goosegroup_manually_given"),
    ]

    operations = [
        migrations.AddField(
            model_name="corp",
            name="manual_group_given_on_approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.goosegroup",
            ),
        ),
    ]
