# Generated by Django 3.1.2 on 2020-12-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_discordguild_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discordroledjangogroupmapping",
            old_name="discord_user",
            new_name="guild",
        ),
        migrations.RenameField(
            model_name="discordroledjangogroupmapping",
            old_name="discord_role_id",
            new_name="role_id",
        ),
    ]
