# Generated by Django 3.1.4 on 2021-02-01 11:17

from django.db import migrations, models
from goosetools.users.models import GooseUser

# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    for g in list(GooseUser.objects.all()):
        g.cache_fields_from_social_account()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210120_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooseuser",
            name="avatar_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gooseuser",
            name="cached_username",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gooseuser",
            name="nick",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gooseuser",
            name="uid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
