# Generated by Django 3.1.4 on 2021-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210201_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="avatar_hash",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="cached_username",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="nick",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="uid",
            field=models.TextField(),
        ),
    ]
