# Generated by Django 3.1.4 on 2021-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20210211_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="connection_valid",
            field=models.BooleanField(default=False),
        ),
    ]
