# Generated by Django 3.1.2 on 2020-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="pre_approved",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gooseuser",
            name="status",
            field=models.TextField(
                choices=[
                    ("unapproved", "unapproved"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="approved",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="default_character",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.character",
            ),
        ),
    ]
