# Generated by Django 3.1.4 on 2021-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_discordguild_connection_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="server_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discordguild",
            name="guild_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
