# Generated by Django 3.1.2 on 2020-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20201209_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discorduser",
            name="pre_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gooseuser",
            name="status",
            field=models.TextField(
                choices=[
                    ("unapproved", "unapproved"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="unapproved",
            ),
        ),
    ]
