# Generated by Django 3.1.4 on 2021-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210203_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="goosegroup",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goosegroup",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
