# Generated by Django 3.1.4 on 2021-02-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210212_1110"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="discord_connection_issue",
            field=models.BooleanField(default=False),
        ),
    ]
