# Generated by Django 3.1.4 on 2021-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20210203_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="goosepermission",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
