# Generated by Django 3.1.4 on 2021-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_discordguild_discord_connection_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="has_manage_roles",
            field=models.BooleanField(default=False),
        ),
    ]
