# Generated by Django 3.1.4 on 2021-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_goosepermission_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authconfig",
            name="new_user_discord_role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goosegroup",
            name="linked_discord_role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="signupquestionchoice",
            name="linked_discord_role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DiscordRole",
        ),
    ]
