# Generated by Django 3.1.2 on 2020-12-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_further_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userapplication",
            old_name="discord_user",
            new_name="user",
        ),
    ]
