# Generated by Django 3.1.4 on 2021-02-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20210203_1224"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "user")},
        ),
    ]
