# Generated by Django 3.1.2 on 2020-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_corp_required_discord_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordroledjangogroupmapping",
            name="grants_staff",
            field=models.BooleanField(default=False),
        ),
    ]
