# Generated by Django 3.1.4 on 2021-02-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20210203_1315"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscordRoleDjangoGroupMapping",
        ),
    ]
