# Generated by Django 3.1.4 on 2021-05-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20210507_2012"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goosepermission",
            name="corp",
        ),
        migrations.CreateModel(
            name="PermissibleEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_or_deny", models.BooleanField()),
                ("order", models.IntegerField()),
                (
                    "corp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.corp",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.goosepermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gooseuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrudAccessController",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deletable_by",
                    models.ManyToManyField(
                        related_name="can_delete", to="users.PermissibleEntity"
                    ),
                ),
                (
                    "editable_by",
                    models.ManyToManyField(
                        related_name="can_edit", to="users.PermissibleEntity"
                    ),
                ),
                (
                    "usable_by",
                    models.ManyToManyField(
                        related_name="can_use", to="users.PermissibleEntity"
                    ),
                ),
                (
                    "viewable_by",
                    models.ManyToManyField(
                        related_name="can_view", to="users.PermissibleEntity"
                    ),
                ),
            ],
        ),
    ]
