# Generated by Django 3.1.2 on 2020-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_discordroledjangogroupmapping_grants_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooseuser",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
