# Generated by Django 3.1.4 on 2021-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20210508_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="crudaccesscontroller",
            name="adminable_by",
            field=models.ManyToManyField(
                related_name="can_admin", to="users.PermissibleEntity"
            ),
        ),
        migrations.AddField(
            model_name="permissibleentity",
            name="built_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="permissibleentity",
            name="allow_or_deny",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="permissibleentity",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
