# Generated by Django 3.1.2 on 2020-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_gooseuser_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
