# Generated by Django 3.1.4 on 2021-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20210204_1010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goosepermission",
            name="name",
            field=models.TextField(
                choices=[
                    (
                        "basic_access",
                        "Able to Apply to join and view the home page and other basic registered user pages",
                    ),
                    ("loot_tracker", "Able to use the loot tracker"),
                    (
                        "loot_tracker_admin",
                        "Automatically an admin in every fleet and able to do loot buyback",
                    ),
                    (
                        "user_admin",
                        "Able to approve user applications and manage users",
                    ),
                    (
                        "user_group_admin",
                        "Able to edit/add user groups and their permissions",
                    ),
                    (
                        "single_corp_admin",
                        "Able to approve corp applications for a specific corp and manage characters in that corp",
                    ),
                    (
                        "all_corp_admin",
                        "Able to approve corp applications for all corps and manage characters in all corps",
                    ),
                    ("ship_orderer", "Able to place ship orders"),
                    ("free_ship_orderer", "Able to place free ship orders"),
                    ("ship_order_admin", "Able to claim and work on ship orders"),
                    (
                        "ship_price_admin",
                        "Able to add/remove ship types and set if they are free or not",
                    ),
                ],
                unique=True,
            ),
        ),
    ]
