# Generated by Django 3.1.2 on 2020-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_discorduser_nick"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordguild",
            name="member_role_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
