# Generated by Django 3.1.4 on 2021-02-08 08:36

import django.db.models.deletion
from django.db import migrations, models


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    Corp = apps.get_model("users", "Corp")
    Character = apps.get_model("users", "Character")
    CorpCopy = apps.get_model("users", "CorpCopy")
    CorpApplication = apps.get_model("users", "CorpApplication")
    UserApplication = apps.get_model("users", "UserApplication")
    for c in Corp.objects.all():
        CorpCopy.objects.create(
            name=c.name,
            full_name=c.full_name,
            required_discord_role=c.required_discord_role,
        )

    for ca in CorpApplication.objects.all():
        ca.corp_new_id = CorpCopy.objects.filter(name=ca.corp.name).first().id
        ca.save()

    for ua in UserApplication.objects.all():
        ua.corp_new_id = CorpCopy.objects.filter(name=ua.corp.name).first().id
        ua.save()

    for ch in Character.objects.all():
        ch.corp_new_id = CorpCopy.objects.filter(name=ch.corp.name).first().id
        ch.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20210205_1121"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpCopy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("full_name", models.TextField(blank=True, null=True, unique=True)),
                ("required_discord_role", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="corp_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.corpcopy",
            ),
        ),
        migrations.AddField(
            model_name="corpapplication",
            name="corp_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.corpcopy",
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="corp_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.corpcopy",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
