# Generated by Django 3.1.4 on 2021-02-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210208_0836"),
        ("items", "0003_auto_20210208_0903"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userapplication",
            name="corp",
        ),
        migrations.RenameField(
            model_name="userapplication",
            old_name="corp_new",
            new_name="corp",
        ),
        migrations.RemoveField(
            model_name="character",
            name="corp",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="corp_new",
            new_name="corp",
        ),
        migrations.RemoveField(
            model_name="corpapplication",
            name="corp",
        ),
        migrations.RenameField(
            model_name="corpapplication",
            old_name="corp_new",
            new_name="corp",
        ),
        migrations.DeleteModel(name="corp"),
        migrations.RenameModel(old_name="corpcopy", new_name="corp"),
    ]
