# Generated by Django 3.1.2 on 2020-12-11 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20201211_2102"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpapplication",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
