# Generated by Django 3.1.2 on 2020-12-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_corpapplication_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="old_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="sa_profile",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.discorduser",
            ),
        ),
    ]
