# Generated by Django 3.1.4 on 2021-02-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0001_initial"),
        ("users", "0019_auto_20210208_1113"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupquestionchoice",
            name="signup_question",
        ),
        migrations.RemoveField(
            model_name="corp",
            name="required_discord_role",
        ),
        migrations.AddField(
            model_name="corp",
            name="sign_up_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_forms.dynamicform",
            ),
        ),
        migrations.DeleteModel(
            name="SignUpQuestion",
        ),
        migrations.DeleteModel(
            name="SignUpQuestionChoice",
        ),
    ]
