# Generated by Django 3.1.2 on 2020-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20201212_1102"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapplication",
            name="activity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="looking_for",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="previous_alliances",
            field=models.TextField(blank=True, null=True),
        ),
    ]
