# Generated by Django 3.1.4 on 2021-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20210208_1442"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discordrole",
            index=models.Index(fields=["name"], name="users_disco_name_ed0024_idx"),
        ),
    ]
