# Generated by Django 3.1.4 on 2021-02-09 10:48

from django.db import migrations, models
import django.db.models.deletion


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    UserApplication = apps.get_model("users", "UserApplication")

    for ua in UserApplication.objects.all():
        ua.answers = {
            "Previous Alliances": ua.previous_alliances,
            "Activity": ua.activity,
            "Looking For": ua.looking_for,
            "Notes From User": ua.application_notes,
        }
        ua.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20210209_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapplication",
            name="answers",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userapplication",
            name="existing_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.character",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
