# Generated by Django 3.1.4 on 2021-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_auto_20210209_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapplication",
            name="answers",
            field=models.JSONField(blank=True),
        ),
    ]
