# Generated by Django 3.1.4 on 2021-01-08 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    DiscordUser = apps.get_model("users", "DiscordUser")

    for discord_user in DiscordUser.objects.all():
        gooseuser = discord_user.gooseuser
        if discord_user.old_notes:
            gooseuser.notes = (
                (gooseuser.notes or "")
                + " #### Notes On This User From Previous AuthBot system: "
                + discord_user.old_notes
            )
        gooseuser.sa_profile = discord_user.sa_profile
        if discord_user.voucher:
            gooseuser.voucher_id = discord_user.voucher.gooseuser.pk
        gooseuser.save()


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    DiscordUser = apps.get_model("users", "DiscordUser")

    for discord_user in DiscordUser.objects.filter().all():
        gooseuser = discord_user.gooseuser
        if discord_user.old_notes and gooseuser.notes:
            gooseuser.notes = gooseuser.notes.split(
                " #### Notes On This User From Previous AuthBot system: "
            )[0]
        gooseuser.sa_profile = None
        gooseuser.voucher = None
        gooseuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_create_gooseusers_from_discord_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooseuser",
            name="sa_profile",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gooseuser",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_vouches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
