# Generated by Django 3.1.4 on 2021-01-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_auto_20210108_1251"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discorduser",
            name="pre_approved",
        ),
    ]
