# Generated by Django 3.1.4 on 2021-01-08 13:09

from django.db import migrations

# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    DiscordUser = apps.get_model("users", "DiscordUser")
    for discord_user in DiscordUser.objects.filter().all():
        discord_user.gooseuser.username = discord_user.username
        discord_user.gooseuser.save()


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_remove_discorduser_pre_approved"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
