# Generated by Django 3.1.4 on 2021-01-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20210112_1643"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discorduser",
            name="avatar_hash",
        ),
    ]
