# Generated by Django 3.1.4 on 2021-01-13 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    Character = apps.get_model("users", "Character")
    for c in Character.objects.all():
        c.user = c.discord_user.gooseuser
        c.save()


# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_remove_discorduser_avatar_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="discord_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.discorduser",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
