# Generated by Django 3.1.4 on 2021-01-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_auto_20210113_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="discord_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.discorduser",
            ),
        ),
    ]
