# Generated by Django 3.1.4 on 2021-01-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_auto_20210113_1159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="discord_user",
        ),
        migrations.RemoveField(
            model_name="gooseuser",
            name="discord_user",
        ),
        migrations.AlterField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.gooseuser"
            ),
        ),
        migrations.DeleteModel(
            name="DiscordUser",
        ),
    ]
