# Generated by Django 3.1.4 on 2021-01-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "__first__"),
        ("users", "0032_auto_20210113_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooseuser",
            name="site_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.siteuser",
            ),
        ),
    ]
