# Generated by Django 3.1.4 on 2021-01-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_auto_20210115_1136"),
        ("users", "0033_gooseuser_site_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="site_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.siteuser"
            ),
        ),
    ]
