# Generated by Django 3.1.4 on 2021-01-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_sync_match_user"),
        ("users", "0034_auto_20210115_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gooseuser",
            name="site_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.siteuser"
            ),
        ),
    ]
