# Generated by Django 3.1.4 on 2021-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_auto_20210115_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapplication",
            name="ingame_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
