# Generated by Django 3.1.4 on 2021-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ownership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="transfer_method",
            field=models.TextField(default="eggs"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transferlog",
            name="deposit_command",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transferlog",
            name="transfer_command",
            field=models.TextField(blank=True, default=""),
        ),
    ]
