# Generated by Django 3.1.2 on 2020-11-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ownership", "0002_auto_20201124_1647"),
    ]

    operations = [
        migrations.AddField(
            model_name="lootgroup",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
