# Generated by Django 3.1.4 on 2021-05-01 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ownership", "0002_auto_20210213_1704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lootbucket",
            name="fleet",
        ),
    ]
