# Generated by Django 3.1.2 on 2020-12-01 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ownership", "0003_lootgroup_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="lootgroup",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
