# Generated by Django 3.1.4 on 2021-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ownership", "0004_lootgroup_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="lootgroup",
            name="locked_participation",
            field=models.BooleanField(default=False),
        ),
    ]
