# Generated by Django 3.1.4 on 2021-05-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venmo", "0010_auto_20210516_1134"),
        ("ownership", "0005_lootgroup_locked_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="new_transfer_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="venmo.transfermethod",
            ),
        ),
    ]
