# Generated by Django 3.1.4 on 2021-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ownership", "0006_transferlog_new_transfer_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferlog",
            name="transfer_method",
            field=models.TextField(blank=True, null=True),
        ),
    ]
