# Generated by Django 3.1.4 on 2021-02-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.TextField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("textarea", "large text area"),
                        ],
                        default="text",
                    ),
                ),
                ("title", models.TextField()),
                ("help_text", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_forms.dynamicform",
                    ),
                ),
            ],
        ),
    ]
