# Generated by Django 3.1.4 on 2021-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dynamicform",
            old_name="header_text",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="dynamicform",
            name="title",
            field=models.TextField(),
        ),
    ]
