# Generated by Django 3.1.4 on 2021-02-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0002_auto_20210208_1453"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signupquestion",
            old_name="question_name",
            new_name="question_title",
        ),
    ]
