# Generated by Django 3.1.4 on 2021-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0003_auto_20210208_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupquestion",
            name="question_type",
            field=models.TextField(
                choices=[
                    ("text", "text"),
                    ("number", "number"),
                    ("textarea", "large text area"),
                ],
                default="text",
            ),
        ),
    ]
