# Generated by Django 3.1.4 on 2021-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0005_auto_20210209_0857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formquestion",
            name="is_required",
            field=models.TextField(default=True),
        ),
    ]
