# Generated by Django 3.1.4 on 2021-02-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0006_auto_20210209_0857"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formquestion",
            old_name="question_help_text",
            new_name="help_text",
        ),
        migrations.RenameField(
            model_name="formquestion",
            old_name="question_title",
            new_name="title",
        ),
    ]
