# Generated by Django 3.1.4 on 2021-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_forms", "0007_auto_20210209_0900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formquestion",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
