# Generated by Django 3.1.2 on 2020-11-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("jumps_to_jita", models.PositiveIntegerField(blank=True, null=True)),
                ("security", models.TextField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
            ],
        ),
    ]
