# Generated by Django 3.1.2 on 2020-11-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0084_auto_20201120_1345"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Fleet",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.TextField()),
                        (
                            "loot_type",
                            models.TextField(
                                choices=[
                                    ("Master Looter", "Master Looter"),
                                    ("Free For All", "Free For All"),
                                ],
                                default="Master Looter",
                            ),
                        ),
                        ("gives_shares_to_alts", models.BooleanField(default=False)),
                        ("start", models.DateTimeField()),
                        ("end", models.DateTimeField(blank=True, null=True)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("location", models.TextField(blank=True, null=True)),
                        ("expected_duration", models.TextField(blank=True, null=True)),
                        (
                            "fc",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="FleetMember",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("joined_at", models.DateTimeField(blank=True, null=True)),
                        ("left_at", models.DateTimeField(blank=True, null=True)),
                        ("admin_permissions", models.BooleanField(default=False)),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.character",
                            ),
                        ),
                        (
                            "fleet",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="fleets.fleet",
                            ),
                        ),
                    ],
                    options={
                        "unique_together": {("character", "fleet")},
                    },
                ),
            ],
        ),
    ]
