# Generated by Django 3.1.4 on 2021-01-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("fleets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="fc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.gooseuser"
            ),
        ),
    ]
