# Generated by Django 3.1.2 on 2020-11-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fleets", "0001_initial"),
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="killmail",
            name="looter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.character",
            ),
        ),
        migrations.AddField(
            model_name="fleetmember",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.character"
            ),
        ),
        migrations.AddField(
            model_name="fleetmember",
            name="fleet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fleets.fleet"
            ),
        ),
        migrations.AddField(
            model_name="fleetanom",
            name="anom_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fleets.anomtype"
            ),
        ),
        migrations.AddField(
            model_name="fleetanom",
            name="fleet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fleets.fleet"
            ),
        ),
        migrations.AddField(
            model_name="fleetanom",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.system"
            ),
        ),
        migrations.AddField(
            model_name="fleet",
            name="fc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fleetmember",
            unique_together={("character", "fleet")},
        ),
    ]
