# Generated by Django 3.1.4 on 2021-05-08 09:58

import django.db.models.deletion
from django.db import migrations, models


# noinspection PyPep8Naming
# pylint: disable=unused-argument
def create_initial_controller(apps, schema_editor):
    from goosetools.users.models import LOOT_TRACKER_ADMIN, LOOT_TRACKER

    Fleet = apps.get_model("fleets", "Fleet")
    CrudAccessController = apps.get_model("users", "CrudAccessController")
    PermissibleEntity = apps.get_model("users", "PermissibleEntity")
    GoosePermission = apps.get_model("users", "GoosePermission")

    def allow_perm(perm, built_in=False):
        perm = GoosePermission.objects.get(name=perm)
        return PermissibleEntity.objects.create(permission=perm, built_in=built_in)

    def allow_user(gooseuser, built_in=False):
        return PermissibleEntity.objects.create(user=gooseuser, built_in=built_in)

    for f in Fleet.objects.all():
        controller = CrudAccessController.objects.create()
        controller.adminable_by.add(allow_user(f.fc, built_in=True))
        controller.adminable_by.add(allow_perm(LOOT_TRACKER_ADMIN, built_in=True))
        for fm in f.fleetmember_set.filter(admin_permissions=True).all():
            controller.adminable_by.add(allow_user(fm.character.user))
        controller.viewable_by.add(allow_perm(LOOT_TRACKER))
        controller.usable_by.add(allow_perm(LOOT_TRACKER))
        f.access_controller = controller
        f.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_auto_20210508_0956"),
        ("fleets", "0005_auto_20210502_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="access_controller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.crudaccesscontroller",
            ),
        ),
        migrations.RunPython(create_initial_controller),
        migrations.AlterField(
            model_name="fleet",
            name="access_controller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.crudaccesscontroller",
            ),
        ),
    ]
