# Generated by Django 3.1.4 on 2021-02-13 11:08

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="isk",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="EEI",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="isk_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EEI", "Eve Echoes ISK")],
                default="EEI",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.TextField(
                choices=[
                    ("requested", "requested"),
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("accepted", "accepted"),
                    ("cancelled", "cancelled"),
                ]
            ),
        ),
    ]
