# Generated by Django 3.1.4 on 2021-02-15 09:02

from django.db import migrations, models


# pylint: disable=unused-argument
def combine_names(apps, schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    for c in Contract.objects.all():
        if c.log:
            c.logged_quantity = len(c.log)
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_auto_20210213_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="logged_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(combine_names),
    ]
