# Generated by Django 3.1.4 on 2021-02-08 08:36

from django.db import migrations, models
import django.db.models.deletion

# pylint: disable=unused-argument
def revert_migration(apps, schema_editor):
    pass


# pylint: disable=unused-argument
def apply_migration(apps, schema_editor):
    CorpCopy = apps.get_model("users", "CorpCopy")
    CorpHanger = apps.get_model("items", "CorpHanger")

    for ch in CorpHanger.objects.all():
        ch.corp_new_id = CorpCopy.objects.filter(name=ch.corp.name).first().id
        ch.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210208_0836"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corphanger",
            name="corp_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.corpcopy",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
