# Generated by Django 3.1.4 on 2021-03-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["stack", "location", "loot_group", "contract"],
                name="items_inven_stack_i_596c46_idx",
            ),
        ),
    ]
