# Generated by Django 3.1.2 on 2020-11-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("items", "0002_auto_20201124_1647"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corphanger",
            name="corp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.corp"
            ),
        ),
        migrations.AddField(
            model_name="corphanger",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.station"
            ),
        ),
        migrations.AddField(
            model_name="characterlocation",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.character"
            ),
        ),
        migrations.AddField(
            model_name="characterlocation",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.system",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["-cached_lowest_sell"], name="items_item_cached__72dc0a_idx"
            ),
        ),
    ]
