# Generated by Django 3.1.4 on 2021-02-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_corphanger_corp_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corphanger",
            name="corp",
        ),
        migrations.RenameField(
            model_name="corphanger",
            old_name="corp_new",
            new_name="corp",
        ),
    ]
