# Generated by Django 3.1.4 on 2021-02-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20210208_0910"),
        ("items", "0003_auto_20210208_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corphanger",
            name="corp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.corp"
            ),
        ),
    ]
