# Generated by Django 3.1.2 on 2020-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_auto_20201124_1647"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("tech_level", models.PositiveIntegerField()),
            ],
        ),
    ]
