# Generated by Django 3.1.4 on 2021-05-03 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_inventoryitem_echoes_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="item",
        ),
        migrations.RenameField(
            model_name="inventoryitem", old_name="echoes_item", new_name="item"
        ),
    ]
