# Generated by Django 3.1.4 on 2021-05-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_auto_20210503_0845"),
        ("pricing", "0003_auto_20210503_0844"),
    ]

    operations = [
        migrations.DeleteModel("item"),
        migrations.RenameModel("echoesitem", "item"),
    ]
