# Generated by Django 3.1.4 on 2021-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_swap_to_new_items_table"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="items_echoe_cached__932ffa_idx",
        ),
        migrations.AddField(
            model_name="item",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["-cached_lowest_sell"], name="items_item_cached__72dc0a_idx"
            ),
        ),
    ]
