# Generated by Django 3.1.4 on 2021-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_itemchangeproposal_deleted_existing_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(),
        ),
    ]
